import uikitEn from '@/src/NEUIKit/common/locales/en'
import uikitZh from '@/src/NEUIKit/common/locales/zh'

export type AppLanguagePreference = 'system' | 'zh' | 'en'
export type AppLanguage = 'zh' | 'en'

export const APP_LANGUAGE_OPTIONS = [
  { labelKey: 'languageOptionChinese', value: 'zh' },
  { labelKey: 'languageOptionEnglish', value: 'en' }
] as const

const APP_TRANSLATIONS = {
  zh: {
    tabMessages: '消息',
    tabContacts: '通讯录',
    tabMe: '我的',
    myUnsetNickname: '未设置昵称',
    mySelf: '我',
    myAccountPrefix: '帐号:{account}',
    myAccountCopiedTitle: '已复制账号',
    myAbout: '关于云信',
    mySettings: '设置',
    myCollection: '收藏',
    aboutTitle: '关于云信',
    aboutBrand: '网易云信',
    aboutVersion: '版本号',
    aboutImVersion: 'IM版本号',
    aboutProductInfo: '产品介绍',
    productIntroTitle: '产品介绍',
    productIntroSubtitle: '连接全球用户与企业，提供稳定、可靠、可扩展的实时通信能力。',
    productIntroCapabilityTitle: '产品能力',
    productIntroCapabilityBody:
      '覆盖即时消息、音视频通话、互动直播、聊天室、信令、推送等核心场景，帮助开发者快速构建高质量的互动产品。',
    productIntroScenarioTitle: '适用场景',
    productIntroScenarioBody:
      '社交沟通、企业协作、在线教育、泛娱乐互动、智能硬件连接与更多实时通信业务。',
    settingsTitle: '设置',
    settingsNotification: '消息提醒',
    settingsCloudConversation: '是否开启云端会话',
    settingsEarpieceMode: '听筒模式',
    settingsReadReceipt: '消息已读未读功能',
    settingsAppearance: '外观',
    settingsLanguage: '语言',
    settingsSystemPermissions: '系统授权管理',
    settingsCloudConversationHint: '重新登录后生效',
    settingsCloudConversationConfirmTitle: '切换云端会话',
    settingsCloudConversationConfirmMessage:
      '切换云端会话需要退出当前登录，重新登录后生效。是否继续？',
    settingsLogout: '退出登录',
    settingsLogoutTitle: '退出登录',
    settingsLogoutMessage: '你确认要退出登录？',
    actionCancel: '取消',
    actionConfirm: '确认',
    actionSave: '保存',
    actionDone: '完成',
    actionDoneWithCount: '完成({count})',
    actionBack: '返回',
    settingsLogoutFailed: '退出失败',
    notificationTitle: '消息提醒',
    notificationNewMessage: '新消息通知',
    notificationMethods: '消息提醒方式',
    notificationRing: '响铃模式',
    notificationVibrate: '震动模式',
    notificationPushSettings: '推送设置',
    notificationShowDetail: '通知栏显示消息详情',
    notificationPermissionPrefix: '系统通知权限：',
    notificationPermissionGranted: '已允许',
    notificationPermissionDenied: '已拒绝',
    notificationPermissionUndetermined: '未确定',
    notificationPermissionUnavailable: '不可用',
    notificationRequestAuth: '请求授权',
    notificationOpenSystemSettings: '系统设置',
    permissionsTitle: '系统授权管理',
    permissionNotification: '通知',
    permissionCamera: '相机',
    permissionAlbum: '相册',
    permissionMicrophone: '麦克风',
    permissionStatusGranted: '已允许',
    permissionStatusDenied: '已拒绝',
    permissionStatusUndetermined: '未确定',
    permissionStatusLimited: '部分允许',
    permissionStatusUnavailable: '不可用',
    permissionRequest: '请求授权',
    permissionOpenSettings: '系统设置',
    permissionRefresh: '刷新状态',
    permissionRequestFailed: '授权请求失败',
    permissionOpenSettingsFailed: '打开系统设置失败',
    settingsUpdateFailed: '设置失败',
    requestFailed: '请求失败',
    openFailed: '打开失败',
    commonRetryLater: '请稍后重试',
    languageTitle: '语言',
    languageOptionChinese: '中文',
    languageOptionEnglish: '英文',
    appearanceTitle: '选择外观',
    appearanceBasic: '基础皮肤',
    appearanceBasicDesc: '默认的基础样式',
    appearanceCommon: '通用皮肤',
    appearanceCommonDesc: '切换到通用风格展示',
    appearanceSwitchFailed: '切换失败',
    myDetailTitle: '个人信息',
    myDetailAvatar: '头像',
    myDetailNickname: '昵称',
    myDetailAccount: '账号',
    myDetailGender: '性别',
    myDetailBirthday: '生日',
    myDetailMobile: '手机',
    myDetailEmail: '邮箱',
    myDetailSignature: '个性签名',
    myDetailUnset: '未设置',
    myDetailCopy: '复制',
    copySuccess: '复制成功',
    copyFailed: '复制失败',
    myDetailCopyFailed: '账号复制失败',
    uploadFailed: '上传失败',
    saveFailed: '保存失败',
    birthdayFormatError: '请输入正确的生日，格式为 YYYY-MM-DD',
    birthdayPickHint: '请选择生日日期，保存后将更新为 YYYY-MM-DD',
    photoTake: '拍照',
    photoChooseFromAlbum: '从手机相册选择',
    birthdayYear: '年',
    birthdayMonth: '月',
    birthdayDay: '日',
    genderTitle: '性别',
    genderUnknown: '未知',
    genderMale: '男',
    genderFemale: '女',
    editPlaceholderNickname: '请输入昵称',
    editPlaceholderMobile: '请输入手机号',
    editPlaceholderEmail: '请输入邮箱',
    editPlaceholderSignature: '请输入个性签名',
    mobileFormatError: '请输入正确的手机号',
    emailFormatError: '请输入正确的邮箱',
    profileTitleNickname: '昵称',
    profileTitleMobile: '手机',
    profileTitleEmail: '邮箱',
    profileTitleSignature: '个性签名',
    commonLoadingFailed: '加载失败',
    commonActionFailed: '操作失败',
    commonOpenFailed: '打开失败',
    commonCreateFailed: '创建失败',
    commonSendFailed: '发送失败',
    commonDeleteFailed: '删除失败',
    commonRetry: '重试',
    commonSelect: '选择',
    commonSearch: '搜索',
    commonEdit: '编辑',
    commonClear: '清空',
    commonAgree: '同意',
    commonReject: '拒绝',
    commonRemove: '解除',
    commonDelete: '删除',
    commonExit: '退出',
    commonDismiss: '解散',
    commonTip: '提示',
    commonUnknownAccount: '未知账号',
    commonNotSet: '未设置',
    commonGroupChat: '群聊',
    commonUnnamedGroupChat: '未命名群聊',
    commonMessageMark: '标记',
    commonMessageHistory: '历史记录',
    commonEnableMessageNotification: '开启消息提醒',
    commonChatStickTop: '聊天置顶',
    commonAddToBlacklist: '加入黑名单',
    commonViewFriendCard: '查看好友名片',
    commonAccountLabel: '账号：{account}',
    commonAccountText: '账号:{account}',
    commonNicknameText: '昵称:{name}',
    commonSearchFriendsPlaceholder: '搜索好友',
    commonSearchKeywordPlaceholder: '请输入你要搜索的关键字',
    commonNoMatchingFriends: '未找到匹配好友',
    commonNoSearchResults: '暂无结果',
    commonNoFriends: '暂无好友',
    commonSearchResult: '搜索结果',
    commonFriend: '好友',
    commonTeam: '群聊',
    commonUserNotFound: '该用户不存在',
    commonCreateWithCount: '创建({count})',
    commonCreate: '创建',
    commonSelectedCount: '已选 {count} 人',
    commonSelectUpToCount: '最多可选 {count} 人',
    commonTapAvatarToDeselect: '点击头像取消选择',
    commonSeedMembersAutoJoin: '当前单聊成员将自动加入',
    commonAtMostSelectContacts: '最多只能选择{count}个联系人',
    commonSelectContactsFirst: '请选择联系人',
    commonAiUserLabel: '数字人 · {account}',
    commonPermissionDenied: '权限不足',
    commonOpenSettings: '去设置',
    commonGrantPermissionInSettings: '请在设置页面添加{permission}权限',
    commonPermissionCamera: '相机',
    commonPermissionAlbum: '相册',
    commonPermissionMicrophone: '麦克风',
    commonNetworkUnavailable: '当前网络异常，请检查你的网络设置',
    sdkErrorAccountNotExist: '该账号不存在',
    sdkErrorUserProfileNotExist: '该用户资料不存在',
    sdkErrorFriendApplicationNotExist: '好友申请不存在',
    sdkErrorFriendNotExist: '好友不存在',
    sdkErrorFriendAlreadyExist: '好友已存在',
    sdkErrorSelfFriendOperationNotAllowed: '不能对自己进行好友操作',
    sdkErrorFriendLimit: '好友数量已达上限',
    sdkErrorTeamMemberLimit: '群组人数达到上限',
    sdkErrorJoinedTeamLimit: '加入群组数量超过上限',
    sdkErrorTeamNotExist: '群组不存在',
    sdkErrorAlreadyInTeam: '已在群组',
    sdkErrorInvitationExpired: '邀请已失效',
    sdkErrorVerificationProcessed: '该验证消息已被处理',
    sdkErrorFriendOperationRateLimit: '好友操作过于频繁，请稍后重试',
    sdkErrorFriendHitAntispam: '好友申请内容可能涉及敏感信息，请调整后重试',
    sdkErrorSelfBlockListOperationNotAllowed: '不能对自己进行黑名单操作',
    sdkErrorBlockListLimit: '黑名单数量已达上限',
    sdkErrorMessageNotExist: '消息不存在',
    sdkErrorPinNotExist: '标记消息不存在',
    sdkErrorPinAlreadyExist: '该消息已被标记',
    sdkErrorPinLimit: '标记消息数量已达上限',
    sdkErrorRevokeExpired: '已超过时间无法撤回',
    sdkErrorRevokeNotAllowed: '当前消息不支持撤回',
    sdkErrorAccountInBlockList: '对方已将你拉黑，发送消息失败',
    sdkErrorOperationRateLimit: '操作过于频繁，请稍后重试',
    sdkErrorAntispam: '内容可能涉及敏感信息，请调整后重试',
    sdkErrorFileUploadFailed: '文件上传失败，请稍后重试',
    sdkErrorConnectFailed: '连接失败，请检查网络后重试',
    sdkErrorProtocolSendFailed: '请求发送失败，请稍后重试',
    sdkErrorRequestFailed: '请求失败，请稍后重试',
    sdkErrorCallbackFailed: '回调处理失败，请稍后重试',
    sdkErrorInvalidParameter: '参数错误，请检查后重试',
    sdkErrorTimeout: '请求超时，请稍后重试',
    sdkErrorConversationNotExist: '会话不存在',
    sdkErrorResourceNotExist: '资源不存在',
    sdkErrorResourceAlreadyExist: '资源已存在',
    sdkErrorNoPermission: '暂无权限执行该操作',
    sdkErrorOperationNotAllowed: '当前操作不被允许',
    sdkErrorUnsupported: '暂不支持该操作',
    sdkErrorFeatureNotEnabled: '功能未开通',
    sdkErrorAccountBanned: '用户被禁用',
    sdkErrorAccountChatBanned: '用户被禁言',
    sdkErrorTeamMemberNotExist: '群成员不存在',
    sdkErrorTeamNormalMemberChatBanned: '群普通成员被禁言',
    sdkErrorTeamMemberChatBanned: '群成员被禁言',
    sdkErrorAIRequestLLMFailed: '请求大语言模型失败',
    sdkErrorAIMessagesDisabled: 'AI消息功能未开通',
    sdkErrorNotAIAccount: '不是数字人账号',
    sdkErrorAIBlocklistNotAllowed: '不允许对数字人进行黑名单操作',
    sdkErrorAIRobotTokenInvalid: 'AI机器人Token无效',
    sdkErrorAIRobotBindCodeNotExist: 'AI机器人账号绑定码不存在',
    sdkErrorAIRobotNotBelongToUser: 'AI机器人账号不属于当前用户',
    sdkErrorAIRobotQRCodeAlreadyBound: '该二维码已被绑定',
    commonOnline: '在线',
    commonOffline: '离线',
    offlineText: '当前网络不可用，请检查你的网络设置',
    connectingText: '当前IM连接已断开，正在重连...',
    commonStatusPending: '待处理',
    commonStatusAgreed: '已同意',
    commonStatusRejected: '已拒绝',
    commonStatusExpired: '已过期',
    commonStatusDirectAdded: '已直接添加',
    commonUnknownMessageBody: '[未知消息体]',
    commonMergedChatHistory: '[聊天记录]',
    commonTextMessage: '[文字消息]',
    commonImageMessage: '[图片消息]',
    commonAudioMessage: '[语音消息]',
    commonVideoMessage: '[视频消息]',
    commonLocationMessage: '[地理位置]',
    commonFileMessage: '[文件消息] {name}',
    commonVideoCallMessage: '[视频通话]',
    commonAudioCallMessage: '[音频通话]',
    commonAudioVideoCallMessage: '[音视频通话]',
    commonImageShort: '[图片]',
    commonAudioShort: '[语音]',
    commonLocationShort: '[位置]',
    commonFileShort: '[文件]',
    commonReceiveNewMessage: '你收到一条新消息',
    commonSendFailedShort: '[发送失败]',
    commonSensitiveContentBlocked: '内容可能涉及敏感信息，请调整后发送',
    commonSensitiveContentBlockedWithType: '内容可能涉及{type}, 请调整后发送',
    commonAntispamPornography: '色情',
    commonAntispamAdvertising: '广告',
    commonAntispamAdvertisingLaw: '广告法',
    commonAntispamViolence: '暴恐',
    commonAntispamProhibited: '违禁',
    commonAntispamPolitics: '涉政',
    commonAntispamAbuse: '谩骂',
    commonAntispamSpam: '灌水',
    commonAntispamOther: '其他',
    commonAntispamValue: '涉价值观',
    commonRecallByYou: '你撤回了一条消息',
    commonRecallByOther: '对方撤回了一条消息',
    commonRecalledMessage: '此消息已撤回',
    commonReplySourceMissing: '回复的原消息不存在，无法重发',
    commonReplySourceUnavailable: '该消息已被撤回或删除',
    commonOriginalImageMissing: '原图片不存在，无法重发',
    commonOriginalVideoMissing: '原视频不存在，无法重发',
    commonOriginalFileMissing: '原文件不存在，无法重发',
    commonOriginalAudioMissing: '原语音不存在，无法重发',
    commonOriginalLocationMissing: '原位置不存在，无法重发',
    commonMessageForwardUnsupported: '该消息暂不支持转发',
    messageStoreBlacklistedTip: '对方已将你拉黑，发送消息失败',
    messageStoreFriendDeletedTip: '双方关系已解除，如需沟通，请申请好友验证',
    messageStoreReminderMessage: '【提醒消息】',
    loginTitle: '验证码登录',
    loginHint: '未注册的手机号验证码通过后将自动注册',
    loginMobilePlaceholder: '请输入手机号',
    loginSmsCodePlaceholder: '请输入验证码',
    loginRequestSmsCode: '获取验证码',
    loginRequestSmsCodeCountdown: '{count} 秒后重新获取',
    loginButton: '登录',
    loginSigningInHint: '正在登录并同步基础数据，请稍候',
    loginInvalidSmsRequestMobile: '请输入正确的手机号码',
    loginInvalidMobile: '请输入正确的手机号',
    loginInvalidSmsCode: '请输入正确的验证码',
    loginSmsCodeFailed: '验证码获取失败',
    loginFailed: '登录失败',
    loginOpenServiceFailed: '打开服务协议失败',
    loginOpenPrivacyFailed: '打开隐私政策失败',
    loginConsentTitle: '温馨提示',
    loginConsentBodyPrefix: '该手机号尚未注册，继续登录即表示你已阅读并同意',
    loginConsentService: '《服务协议》',
    loginConsentAnd: '和',
    loginConsentPrivacy: '《隐私政策》',
    loginConsentBodySuffix: '。',
    loginConsentDisagree: '不同意',
    loginConsentAgree: '已阅读并同意',
    p2pSettingsTitle: '聊天设置',
    teamSettingsTitle: '设置',
    teamSettingsLoadFailed: '群设置加载失败',
    teamInfoTitle: '群信息',
    teamDiscussionInfoTitle: '讨论组信息',
    teamSettingsMemberCount: '群成员',
    teamSettingsDiscussionMemberCount: '讨论组成员',
    teamSettingsGroupId: '群号：{teamId}',
    teamSettingsIntro: '群介绍',
    teamSettingsMyNick: '我的群昵称',
    teamSettingsMyNickEditTitle: '我在群里的昵称',
    teamSettingsAvatar: '群头像',
    teamSettingsDiscussionAvatar: '讨论组图像',
    teamSettingsName: '群名称',
    teamSettingsDiscussionName: '讨论组名称',
    teamSettingsManage: '群管理',
    teamSettingsChatBanned: '群禁言',
    teamSettingsInviteMode: '邀请他人权限',
    teamSettingsAddMemberMode: '谁可以添加群成员',
    teamSettingsUpdateInfoMode: '群资料修改权限',
    teamSettingsAgreeMode: '是否需要被邀请者同意',
    teamSettingsInviteModeManager: '群主和管理员',
    teamSettingsInviteModeOwnerAndManager: '群主和管理员',
    teamSettingsInviteModeAll: '所有人',
    teamSettingsAgreeModeNeed: '需要',
    teamSettingsAgreeModeNoNeed: '不需要',
    updateTeamAtText: '谁可以@所有人',
    teamSettingsExitDiscussion: '退出讨论组',
    teamSettingsDismissGroup: '解散群聊',
    teamSettingsExitGroup: '退出群聊',
    teamSettingsExitDiscussionConfirm: '确认退出讨论组？',
    teamSettingsDismissGroupConfirm: '确认解散群聊？',
    teamSettingsExitGroupConfirm: '确认退出群聊？',
    teamInviteMembersFailed: '邀请失败',
    teamInviteCandidatesLoadFailed: '可邀请成员加载失败',
    teamInviteCandidatesNoMatch: '未找到可邀请成员',
    teamInviteCandidatesEmpty: '暂无可邀请成员',
    teamInviteSelectionHint: '选择后将直接邀请加入群聊',
    teamMemberRemoveTitle: '是否移除',
    teamMemberRemoveConfirm: '移除后该成员将离开当前群聊',
    teamMembersLoadFailed: '群成员加载失败',
    teamEditIntroPlaceholder: '请输入群介绍',
    teamEditNickPlaceholder: '请输入我的群昵称',
    teamEditAvatarTitle: '修改头像',
    contactsBlacklistTitle: '黑名单',
    contactsBlacklistTip: '你不会收到列表中任何联系人的消息',
    contactsBlacklistEmpty: '暂无黑名单成员',
    contactsBlacklistPickerEmpty: '暂无可选好友',
    contactsBlacklistAddFailed: '加入黑名单失败',
    contactsBlacklistLoadFailed: '黑名单加载失败',
    contactsBlacklistRemoveTitle: '移出黑名单',
    contactsBlacklistRemoveConfirm: '确认将该联系人移出黑名单？',
    contactsValidListTitle: '验证消息',
    contactsValidListEmpty: '暂无验证消息',
    contactsValidListLoadFailed: '验证消息加载失败',
    contactsValidListClearTitle: '清空验证消息',
    contactsValidListClearConfirm: '确认清空当前验证消息记录？',
    contactsValidListClearFailed: '清空失败',
    contactsValidListClearSuccess: '清空成功',
    contactsValidListRejectFailed: '拒绝失败',
    contactsValidListAcceptFailed: '同意失败',
    contactsValidListFriendRequest: '{name} 好友申请',
    contactsValidListFriendRequestAction: '申请添加为好友',
    contactsValidListAgreedYourRequest: '{name} 同意了你的好友请求',
    contactsValidListRejectedYourRequest: '{name} 拒绝了你的好友请求',
    friendAcceptGreetingText: '我已经同意了你的申请，现在开始聊天吧~',
    friendRemarkTitle: '备注名',
    contactsTeamListTitle: '我的群聊',
    contactsTeamListEmpty: '暂无群聊',
    contactsTeamListLoadFailed: '群聊列表加载失败',
    contactsTeamListInvalidConversation: '当前群聊会话不可用',
    contactsAiUsersTitle: '我的数字人',
    contactsAiUsersEmpty: '暂无数字人',
    contactsAiUsersLoadFailed: '数字人列表加载失败',
    contactsAiUsersInvalidConversation: '当前数字人会话不可用',
    aiUserCardTitle: '数字人名片',
    friendCardTitle: '好友名片',
    strangerCardTitle: '陌生人名片',
    friendCardAlias: '备注名',
    friendCardBirthday: '生日',
    friendCardMobile: '手机',
    friendCardEmail: '邮箱',
    friendCardSignature: '个性签名',
    friendCardMessageNotification: '消息提醒',
    friendCardChat: '聊天',
    friendCardDelete: '删除好友',
    friendCardDeleteConfirm: '将联系人{name}删除？',
    friendCardAdd: '添加好友',
    friendCardAddSentTitle: '已发送',
    friendCardAddSentBody: '好友申请已发送',
    friendCardDefaultPostscript: '你好，我是 RN Demo 用户',
    friendAddTitle: '添加好友',
    friendAddPlaceholder: '请输入账号',
    friendAddEmptyTitle: '未找到相关账号',
    friendAddEmptySubtitle: '请确认输入的账号是否正确。',
    conversationSearchTitle: '搜索',
    conversationSearchCreateTeam: '建群',
    conversationSearchInvalidFriend: '该联系人已失效，请重新选择有效联系人',
    conversationSearchLeftTeam: '您已被移出群聊或群聊已解散',
    conversationPickerCancel: '取消',
    conversationPickerNoSelectableFriends: '暂无可选好友',
    conversationListTitle: '云信 Demo',
    conversationListNoMessage: '暂无消息',
    conversationListPin: '置顶',
    conversationListUnpin: '取消置顶',
    conversationListPinConversation: '置顶会话',
    conversationListDeleteConversation: '删除会话',
    conversationListDeletingConversation: '删除中...',
    conversationListCurrentConversation: '当前会话',
    conversationListDeleteConfirmTitle: '将会话“{title}”删除',
    conversationListAddFriend: '添加好友',
    conversationListJoinGroup: '加入群组',
    conversationListCreateDiscussion: '创建讨论组',
    conversationListCreateAdvancedGroup: '创建高级群',
    conversationListOperationFailedTitle: '操作失败',
    conversationListDeleteFailedTitle: '删除失败',
    teamJoinTitle: '加入群组',
    teamJoinPlaceholder: '请输入群号',
    teamJoinSearchEmpty: '请输入群号后再搜索',
    teamJoinNoResult: '该群组不存在',
    teamJoinApply: '申请入群',
    teamJoinAlreadyJoined: '已加入',
    teamJoinGoChat: '去聊天',
    teamJoinGoChatFailed: '去聊天失败',
    teamJoinApplySuccess: '入群申请已发送',
    teamJoinApplyFailed: '申请入群失败',
    teamTypeDiscussion: '讨论组',
    teamTypeAdvanced: '高级群',
    conversationPickerCreateDiscussionTitle: '创建讨论组',
    conversationPickerCreateAdvancedTitle: '创建高级群',
    conversationPickerCreateDiscussionAction: '创建讨论组',
    conversationPickerCreateAdvancedAction: '创建高级群',
    contactsHomeSummary: '好友 {friendCount} 位 · 群 {teamCount} 个',
    conversationMentionPrefix: '[有人@我] ',
    conversationMentionBadge: '[有人@我]',
    toolbarVoice: '语音',
    toolbarEmoji: '表情',
    toolbarMore: '更多',
    commonSendFailedLabel: '发送失败',
    commonTipMessagePreview: '[提示消息]',
    commonUnknownSize: '未知大小',
    commonUnknownShort: '未知',
    commonDownloading: '下载中...',
    commonDownload: '下载',
    commonPlay: '播放',
    commonSending: '发送中...',
    commonDurationLabel: '时长 {duration}',
    commonFileMessageLabel: '文件消息',
    commonVideoMessageLabel: '视频消息',
    commonDownloadedSize: '已下载 · {size}',
    chatMergedForwardFooter: '聊天记录',
    chatPinnedByYou: '你标记了这条信息',
    chatPinnedMessage: '标记了这条信息',
    chatSecurityTip:
      '仅用于体验云信产品功能，请勿轻信汇款、中奖等涉及钱款的信息，勿拨打陌生电话，谨防受骗。',
    chatSecurityTipReportLink: '点击举报。',
    chatNonFriendTip: '当前不是您的好友，请注意保护个人隐私安全',
    chatTeamDismissedTip: '该群聊已解散',
    chatTeamUnavailableTip: '当前群聊已解散或你已不在该群聊',
    chatTeamBannedPlaceholder: '当前群主设置为禁言',
    chatTimeLabelSameYear: '{month}/{day} {time}',
    chatTimeLabelFullYear: '{year}/{month}/{day} {time}',
    chatUnsupportedFormat: '暂不支持该格式',
    chatVideoTooLarge: '视频最大支持100M，超过无法发送',
    chatActionCopy: '复制',
    chatActionReply: '回复',
    chatActionForward: '转发',
    chatActionPin: '标记',
    chatActionUnpin: '取消标记',
    chatActionMultiSelect: '多选',
    chatActionCollect: '收藏',
    chatActionUncollect: '取消收藏',
    chatActionResend: '重发',
    chatActionRevoke: '撤回',
    chatEmptyMessageUnsupported: '不支持发送空消息',
    chatSendMessageFailed: '消息发送失败',
    chatMixedMediaUnsupported: '图片和视频不能混合选择',
    chatSingleVideoOnly: '视频只支持单个选择',
    chatSendMediaFailed: '媒体发送失败',
    chatSendOriginalVideoFailed: '原视频发送失败',
    chatSendOriginalImageFailed: '原图发送失败',
    chatLimitedPhotoAccessTitle: '照片访问范围受限',
    chatLimitedPhotoAccessMessage: '当前仅可访问已授权照片，可继续选择或添加更多照片',
    chatChoosePhotos: '去选择',
    chatAddMorePhotos: '添加更多照片',
    chatLimitedPhotoAccessUnsupported:
      '当前环境不支持直接补充可访问照片，请在系统设置中调整相册权限',
    chatLimitedMediaPickerTitle: '图片和视频',
    chatFileAlbumPickerTitle: '相册文件',
    chatLimitedMediaPickerEmpty: '暂无可访问的照片或视频',
    chatLimitedMediaPickerConfirm: '确定',
    chatLimitedMediaPickerLoading: '正在加载已授权媒体...',
    chatSelectMediaUpToCount: '最多可选 {count} 项',
    chatOpenCameraActionsTitle: '拍摄',
    chatTakePhoto: '拍照',
    chatRecordVideo: '摄像',
    chatFileSourceTitle: '选择文件来源',
    chatFileSourceAlbum: '从相册选择',
    chatFileSourceICloud: '从 iCloud 选择',
    chatFileTooLarge: '当前文件大小超出100M发送限制，请重新选择',
    chatUploadRequestTooLarge: '文件体积过大，发送失败',
    chatSendFileFailed: '文件发送失败',
    chatNativeLocationUnavailableTitle: '原生地图不可用',
    chatNativeLocationUnavailableMessage:
      '当前 Android 包未注册 NIMLocationPicker，请重新编译安装应用。',
    chatOpenNativeLocationFailedTitle: '打开高德地图失败',
    chatOpenNativeLocationFailedMessage: '原生位置选择器打开失败',
    chatRecordFailedTitle: '录音失败',
    chatRecordStartFailed: '无法开始录音',
    chatRecordFileMissing: '未生成可发送的语音文件',
    chatRecordTooShort: '说话时间太短',
    chatSendAudioFailed: '语音发送失败',
    chatLoadEarlierMessagesFailed: '无法加载更早消息',
    chatDetailTitle: '聊天详情',
    chatSourceMessageTitle: '源消息',
    chatPeerTyping: '正在输入中...',
    chatVoiceAction: '语音',
    chatImageAction: '图片',
    chatMoreAction: '更多',
    chatSelectDoneCount: '已选择 {count} 条消息',
    chatPullToLoadHistory: '下拉查看历史消息',
    chatNoMessages: '暂无消息',
    chatNewMessageNotice: '有新消息',
    chatNewMessageNoticeCount: '{count}条新消息',
    chatActionFailedTitle: '操作失败',
    chatActionFailedMessage: '当前操作执行失败',
    chatMentionSelectTitle: '选择提醒的人',
    chatMentionSearchPlaceholder: '搜索群成员',
    chatMentionNoMatch: '未找到群成员',
    chatMentionEmpty: '暂无可提醒成员',
    chatBatchForwardMerged: '合并转发',
    chatBatchForwardSerial: '逐条转发',
    chatReplyTo: '回复 {name}',
    chatVoiceReleaseToSend: '松开发送，滑到空白区域取消',
    chatVoiceReleaseToCancel: '松开取消发送',
    chatVoiceProcessing: '处理中...',
    chatHoldToTalk: '按住说话',
    chatSendToConversation: '发送给 {name}',
    chatPanelCapture: '拍摄',
    chatPanelFile: '文件',
    chatPanelLocation: '位置',
    chatOpenMessageFailed: '无法打开该消息',
    chatReplySourceDownloading: '正在下载',
    chatReeditExpired: '已超过可编辑时间',
    chatResendUnsupported: '暂不支持重发该消息',
    chatBatchForwardSerialLimit: '逐条转发限制{count}条消息',
    chatBatchForwardMergedLimit: '合并转发限制{count}条消息',
    chatMergedForwardTrimConfirm: '存在超出合并限制的消息，无法合并转发，是否去除后发送',
    chatForwardUnsupportedMessages: '存在不可转发的消息体',
    chatBatchDeleteLimit: '批量删除限制{count}条消息',
    chatDeleteMessageTitle: '删除消息',
    chatDeleteSelectedConfirm: '确认删除选中的消息？',
    chatDeleteSingleConfirm: '确认删除该消息？',
    chatRevokeFailedTitle: '撤回失败',
    chatRevokeExpired: '已超过时间无法撤回',
    chatRevokeMessageTitle: '撤回消息',
    chatRevokeConfirm: '确认撤回该消息？',
    chatPinSuccess: '标记成功',
    chatUnpinSuccess: '取消标记成功',
    chatPinFailed: '标记失败',
    chatUnpinFailed: '取消标记失败',
    chatCollectSuccess: '收藏成功',
    chatUncollectSuccess: '取消收藏成功',
    chatCollectFailed: '收藏失败',
    chatUncollectFailed: '取消收藏失败',
    chatVideoUnavailable: '当前视频不存在或尚未可用',
    chatDownloadingTitle: '请稍候',
    chatVideoDownloading: '当前视频正在下载中',
    chatDownloadCompletedTitle: '下载完成',
    chatVideoDownloaded: '视频已缓存，再次点击即可播放',
    chatVideoDownloadFailed: '视频下载失败',
    chatFileUnavailable: '当前文件不存在或尚未可用',
    chatFileDownloading: '当前文件正在下载中',
    chatFileDownloaded: '文件已保存到本地，再次点击即可打开',
    chatFileDownloadFailed: '文件下载失败',
    chatFileOpenFailed: '当前文件无法打开',
    chatAudioUnavailable: '当前语音不存在或尚未可用',
    chatAudioPlayFailedTitle: '播放失败',
    chatAudioPlayFailed: '当前语音无法播放',
    chatCopySuccess: '复制成功',
    locationPickerCoordinateAddress: '位置：{latitude}, {longitude}',
    locationPickerMapLoading: '地图加载中',
    locationPickerLocationFailedTitle: '定位失败',
    locationPickerLocationFailedMessage: '请搜索或移动地图选择位置。',
    locationPickerSendUnavailableTitle: '无法发送',
    locationPickerSendUnavailableMessage: '请选择一个位置。',
    locationPickerTitle: '选择位置',
    locationPickerConversationUnavailableTitle: '会话不存在',
    locationPickerConversationUnavailableDescription: '无法为当前会话发送位置消息。',
    locationPickerLocating: '正在定位...',
    locationPickerLoadingMap: '正在加载地图...',
    locationPickerSearchPlaceholder: '搜索地点',
    locationPickerPermissionTip: '未开启定位权限，可搜索地点或移动地图选择位置。',
    locationPickerSearching: '正在搜索位置...',
    locationPickerEmpty: '暂无位置',
    readDetailLoadFailed: '阅读状态加载失败',
    readDetailAllUnread: '全部成员未读',
    readDetailAllRead: '全部成员已读',
    readDetailTitle: '消息阅读状态',
    readDetailEmptyTitle: '暂无阅读状态',
    readDetailEmptyDescription: '当前消息还没有可展示的已读未读详情。',
    readDetailReadTab: '已读({count})',
    readDetailUnreadTab: '未读({count})',
    readDetailRealtimeDescription: '阅读状态会随着消息回执实时更新。',
    mediaViewerMissingTitle: '媒体不存在',
    mediaViewerMissingDescription: '当前图片或视频还没有同步完成。',
    mediaViewerSaveFailedTitle: '保存失败',
    mediaViewerMissingMedia: '媒体资源不存在',
    mediaViewerSaveUnsupported:
      '当前 Expo Go 环境不支持保存到系统相册，请使用开发构建或原生包验证保存能力。',
    mediaViewerNeedPhotoPermission: '请在系统设置中开启相册权限',
    mediaViewerSavedToAlbum: '已保存到系统相册',
    mediaViewerSaveSuccessTitle: '保存成功',
    mediaViewerOpenFailedTitle: '打开失败',
    mediaViewerOriginalMissing: '原始媒体地址不存在',
    mediaViewerOriginalAddressTitle: '原始地址',
    mediaViewerImageMissingTitle: '图片资源不存在',
    mediaViewerImageMissingDescription: '请返回聊天页后重新尝试打开。',
    mediaViewerImageSaveFailed: '图片保存失败',
    mediaViewerVideoSaveFailed: '视频保存失败',
    mediaViewerVideoMissingTitle: '视频资源不存在',
    mediaViewerVideoMissingDescription: '请返回聊天页后重新尝试打开。',
    fileDetailSourceChat: '聊天中的文件',
    fileDetailSourceCollection: '收藏中的文件',
    fileDetailSendToCurrentConversation: '发送给 当前会话',
    fileDetailSavedTitle: '文件已保存',
    fileDetailDownloadSuccessTitle: '下载成功',
    fileDetailSavedDescription: '文件已保存到本地',
    fileDetailDownloadFailed: '文件保存失败',
    fileDetailUnavailableTitle: '文件不存在',
    fileDetailUnavailableDescription: '当前文件还没有同步完成，稍后再试。',
    fileDetailChatHint: '当前展示这条聊天消息里的文件。',
    fileDetailCollectionHint: '当前展示已打开文件的收藏态壳层，后续可接入真实收藏列表。',
    fileDetailOpeningStatus: '文件打开中',
    fileDetailDownloadingStatus: '文件下载中',
    fileDetailDownloadedStatus: '已下载，可直接打开',
    fileDetailPendingStatus: '未下载，打开时会自动缓存',
    fileDetailOpening: '打开中...',
    fileDetailOpenFile: '打开文件',
    fileDetailDownloadAndOpen: '下载并打开',
    fileDetailSaving: '保存中...',
    fileDetailSaved: '已保存',
    fileDetailSaveFile: '保存文件',
    forwardModeSerial: '逐条转发',
    forwardModeMerged: '合并转发',
    forwardModeSingle: '转发',
    forwardGroupMemberCount: '{count}人',
    forwardNoMessages: '未找到可转发的消息',
    forwardPreviewConversationRecord: '[{mode}]{title}的会话记录',
    forwardRecentLoadFailed: '最近转发加载失败',
    forwardUnavailableTitle: '无法转发',
    forwardUnavailableMessage: '目标会话已失效，请重新选择有效的联系人或群聊',
    forwardMaxTargets: '最多只能选择{count}个会话',
    forwardSelectAtLeastOne: '请至少选择一个有效会话',
    forwardSelectValidTarget: '请选择有效的转发会话',
    forwardFailedTitle: '转发失败',
    forwardUnsupportedFormat: '暂不支持该格式',
    forwardMergedLimitExceeded: '存在超出合并限制的消息，无法合并转发',
    forwardSystemFailure: '系统异常，转发失败',
    forwardHeaderSelect: '选择',
    forwardHeaderMultiSelect: '多选',
    forwardSelectedConversations: '已选择 {count} 个会话',
    forwardSectionRecent: '最近转发',
    forwardSectionRecentChats: '最近聊天',
    forwardSectionFriends: '我的好友',
    forwardSectionGroups: '我的群聊',
    forwardRecentLoadFailedTitle: '最近转发加载失败',
    forwardSearchNoResultPrefix: '未搜索到',
    forwardSearchNoResultSuffix: '相关结果',
    forwardNoConversations: '暂无会话',
    forwardNoConversationsDescription: '进入聊天后可从最近会话里快速转发。',
    forwardNoFriendsDescription: '请先添加好友后再转发消息。',
    forwardNoGroups: '暂无群聊',
    forwardNoGroupsDescription: '加入群聊后可以把消息转发到这里。',
    forwardSendToTitle: '发送给',
    forwardCommentPlaceholder: '留言',
    forwardSelectedTitle: '已选',
    forwardSelectedEmpty: '暂无已选择会话',
    collectionTitle: '收藏',
    collectionImageBadge: '图片',
    collectionImageHelper: '图片消息预览',
    collectionVideoBadge: '视频',
    collectionVideoHelper: '视频消息预览',
    collectionFileBadge: '文件',
    collectionFileHelper: '文件消息预览',
    collectionLocationBadge: '位置',
    collectionLocationHelper: '位置消息预览',
    collectionLoadFailed: '收藏列表加载失败',
    collectionEmptyTitle: '暂无收藏',
    collectionEmptySubtitle: '收藏的消息会显示在这里',
    collectionUnknownConversation: '未知会话',
    collectionOriginalMessageUnavailable: '原消息不存在或尚未同步',
    collectionPreviewFallback: '收藏消息',
    collectionUnknownSender: '未知发送者',
    collectionSourcePrefix: '来自 {name}',
    collectionP2PSourcePrefix: '来自于 与{name}的会话',
    collectionTeamSourcePrefix: '来自于 {name}',
    collectionRemoveFailed: '删除收藏失败',
    collectionRemoveAction: '删除',
    collectionDeleteConfirm: '确认要删除该收藏吗？',
    collectionDeleteSuccess: '删除成功',
    collectionResolveFailed: '信息获取失败',
    collectionProcessing: '处理中...',
    collectionForwardAction: '转发',
    mergedForwardDownloadFailed: '聊天记录下载失败',
    mergedForwardMessagesTitle: '{name}的消息',
    mergedForwardTitleSuffix: '的消息',
    mergedForwardNotFound: '聊天记录不存在',
    mergedForwardFetchFailed: '信息获取失败',
    mergedForwardAttachmentOpenUnsupported: '当前设备无法直接打开该附件',
    mergedForwardOpenMessageFailed: '当前消息无法打开',
    mergedForwardLoading: '加载中...',
    mergedForwardUnavailableDescription: '当前合并转发内容还没有同步完成。',
    conversationPreviewNoDetailAddress: '暂无详细地址',
    chatReportTitle: '举报',
    chatReportLoadFailed: '举报页面加载失败',
    chatReportLoadFailedDescription: '请检查当前网络后重试。',
    commonReload: '重新加载',
    locationDetailUnavailableTitle: '位置消息不存在',
    locationDetailUnavailableDescription: '当前地理位置还没有同步完成，稍后再试。',
    locationDetailBack: '返回',
    locationDetailNavigate: '导航',
    locationDetailOpenFailed: '打开失败',
    locationDetailNavigationUnavailable: '无法导航',
    locationDetailCoordinateUnavailable: '当前位置坐标不可用',
    locationDetailMapUnavailable: '当前设备无法打开地图',
    locationDetailMapOpenUnavailable: '当前地图无法打开',
    commonLocationTitle: '位置',
    chatHistoryTitle: '历史记录',
    chatHistorySearchPlaceholder: '搜索聊天记录',
    chatHistoryCurrentConversation: '当前会话',
    chatHistorySummary: '共 {count} 条消息',
    chatHistoryLoadFailed: '历史消息加载失败',
    chatHistoryLoadMoreFailed: '无法加载更早消息',
    chatHistoryLoadMore: '加载更早消息',
    chatHistoryEmpty: '暂无历史消息',
    chatHistoryNoMatch: '没有匹配的历史消息',
    chatHistoryNoMatchDescription: '换一个关键词试试，或者先加载更早的消息。',
    chatHistoryAudioUnavailable: '当前语音不存在或尚未可用',
    chatHistoryAttachmentUnavailable: '当前设备无法直接打开该附件',
    commonMessageUnavailableOpen: '当前消息无法打开',
    pinnedMessagesTitle: '标记',
    pinnedMessagesLoading: '加载中...',
    pinnedMessagesSyncingDescription: '正在同步当前会话的标记消息。',
    pinnedMessagesLoadFailed: '标记消息加载失败',
    pinnedMessagesEmpty: '暂无标记消息',
    pinnedMessagesEmptyDescription: '在聊天页长按消息后，可以把重要内容标记到这里。',
    pinnedMessagesUnpinFailed: '取消标记失败',
    pinnedMessagesCopyFailed: '当前消息无法复制',
    messagePreviewTitle: '消息详情',
    messagePreviewMissingTitle: '消息不存在',
    messagePreviewMissingDescription: '当前内容还没有同步到本地，稍后再试。',
    messagePreviewOutgoingTitle: '我发送的内容',
    messagePreviewIncomingTitle: '消息内容',
    messagePreviewCopyContent: '复制内容',
    messagePreviewCopyFailed: '内容复制失败',
    messagePreviewSendToConversation: '发送给 当前会话',
    messagePreviewSendToNamedConversation: '发送给 {name}',
    messagePreviewOriginalAddressLabel: '原始地址',
    messagePreviewOriginalAddressCopyAction: '复制完整原始地址',
    messagePreviewOriginalAddressCopied: '原始地址已复制',
    messagePreviewOriginalAddressCopyFailed: '原始地址复制失败',
    messagePreviewOriginalAddressWarning: '请妥善保管，不要泄露给他人',
    teamNotificationJoinedGroup: '{name} 加入群组',
    teamNotificationInviteMembers: '{inviter}邀请{members}加入群聊',
    teamNotificationInviteNewMembers: '{inviter}邀请新成员加入群聊',
    teamNotificationMembersRemoved: '{members} 被移出群聊',
    teamNotificationMemberRemoved: '有成员被移出群聊',
    teamNotificationLeftGroup: '{name}退出了群聊',
    teamNotificationOwnerTransferred: '{name} 成为新群主',
    teamNotificationOwnerTransferredFallback: '群主已转让',
    teamNotificationRenamedGroup: '{name}修改群名称为{groupName}',
    teamNotificationUpdatedAvatar: '{name} 更新了群头像',
    teamNotificationUpdatedIntro: '{name} 更新了群介绍',
    teamNotificationUpdatedInfo: '群信息已更新',
    teamNotificationUpdatedInviteMode: '更新了群权限“邀请他人权限”为“{value}”',
    teamNotificationUpdatedInfoMode: '更新了群权限“群资料修改权限”为“{value}”',
    teamNotificationUpdatedChatBanned: '更新了“群禁言”为{value}',
    teamNotificationUpdatedAllowAt: '@所有人权限更新为{value}',
    teamNotificationValueAll: '所有人',
    teamNotificationValueOwnerOnly: '仅群主',
    teamNotificationValueOwnerAndManager: '群主和管理员',
    teamNotificationValueOpen: '开启',
    teamNotificationValueClose: '关闭'
  },
  en: {
    tabMessages: 'Messages',
    tabContacts: 'Contacts',
    tabMe: 'Me',
    myUnsetNickname: 'No nickname',
    mySelf: 'Me',
    myAccountPrefix: 'Account: {account}',
    myAccountCopiedTitle: 'Account copied',
    myAbout: 'About Netease IM',
    mySettings: 'Settings',
    myCollection: 'Collection',
    aboutTitle: 'About Netease IM',
    aboutBrand: 'Netease IM',
    aboutVersion: 'Version',
    aboutImVersion: 'IM Version',
    aboutProductInfo: 'Product Info',
    productIntroTitle: 'Product Info',
    productIntroSubtitle:
      'Connect users and businesses worldwide with stable, reliable, and scalable real-time communication.',
    productIntroCapabilityTitle: 'Capabilities',
    productIntroCapabilityBody:
      'Cover instant messaging, audio and video calls, live interaction, chatrooms, signaling, and push scenarios to help developers build high-quality interactive products quickly.',
    productIntroScenarioTitle: 'Scenarios',
    productIntroScenarioBody:
      'Social communication, enterprise collaboration, online education, entertainment interaction, smart device connectivity, and more real-time communication scenarios.',
    settingsTitle: 'Settings',
    settingsNotification: 'Notifications',
    settingsCloudConversation: 'Enable Cloud Conversation',
    settingsEarpieceMode: 'Earpiece Mode',
    settingsReadReceipt: 'Read Receipts',
    settingsAppearance: 'Appearance',
    settingsLanguage: 'Language',
    settingsSystemPermissions: 'System Permissions',
    settingsCloudConversationHint: 'Takes effect after you log in again',
    settingsCloudConversationConfirmTitle: 'Switch Cloud Conversation',
    settingsCloudConversationConfirmMessage:
      'Switching cloud conversation requires logging out of the current session and takes effect after you log in again. Continue?',
    settingsLogout: 'Log out',
    settingsLogoutTitle: 'Log out',
    settingsLogoutMessage: 'Are you sure you want to log out?',
    actionCancel: 'Cancel',
    actionConfirm: 'Confirm',
    actionSave: 'Save',
    actionDone: 'Done',
    actionDoneWithCount: 'Done ({count})',
    actionBack: 'Back',
    settingsLogoutFailed: 'Log out failed',
    notificationTitle: 'Notifications',
    notificationNewMessage: 'New Message Notifications',
    notificationMethods: 'Alert Methods',
    notificationRing: 'Sound',
    notificationVibrate: 'Vibration',
    notificationPushSettings: 'Push Settings',
    notificationShowDetail: 'Show Message Details',
    notificationPermissionPrefix: 'System notification permission: ',
    notificationPermissionGranted: 'Granted',
    notificationPermissionDenied: 'Denied',
    notificationPermissionUndetermined: 'Undetermined',
    notificationPermissionUnavailable: 'Unavailable',
    notificationRequestAuth: 'Request Permission',
    notificationOpenSystemSettings: 'System Settings',
    permissionsTitle: 'System Permissions',
    permissionNotification: 'Notifications',
    permissionCamera: 'Camera',
    permissionAlbum: 'Photos',
    permissionMicrophone: 'Microphone',
    permissionStatusGranted: 'Granted',
    permissionStatusDenied: 'Denied',
    permissionStatusUndetermined: 'Undetermined',
    permissionStatusLimited: 'Limited',
    permissionStatusUnavailable: 'Unavailable',
    permissionRequest: 'Request',
    permissionOpenSettings: 'System Settings',
    permissionRefresh: 'Refresh',
    permissionRequestFailed: 'Permission request failed',
    permissionOpenSettingsFailed: 'Failed to open system settings',
    settingsUpdateFailed: 'Update failed',
    requestFailed: 'Request failed',
    openFailed: 'Open failed',
    commonRetryLater: 'Please try again later',
    languageTitle: 'Language',
    languageOptionChinese: 'Chinese',
    languageOptionEnglish: 'English',
    appearanceTitle: 'Appearance',
    appearanceBasic: 'Basic Skin',
    appearanceBasicDesc: 'Default basic style',
    appearanceCommon: 'Common Skin',
    appearanceCommonDesc: 'Switch to the common visual style',
    appearanceSwitchFailed: 'Switch failed',
    myDetailTitle: 'Profile',
    myDetailAvatar: 'Avatar',
    myDetailNickname: 'Nickname',
    myDetailAccount: 'Account',
    myDetailGender: 'Gender',
    myDetailBirthday: 'Birthday',
    myDetailMobile: 'Phone',
    myDetailEmail: 'Email',
    myDetailSignature: 'Signature',
    myDetailUnset: 'Not set',
    myDetailCopy: 'Copy',
    copySuccess: 'Copied',
    copyFailed: 'Copy failed',
    myDetailCopyFailed: 'Failed to copy account',
    uploadFailed: 'Upload failed',
    saveFailed: 'Save failed',
    birthdayFormatError: 'Enter a valid birthday in YYYY-MM-DD format',
    birthdayPickHint: 'Pick a birthday date. It will be saved as YYYY-MM-DD.',
    photoTake: 'Take Photo',
    photoChooseFromAlbum: 'Choose from Album',
    birthdayYear: 'Year',
    birthdayMonth: 'Month',
    birthdayDay: 'Day',
    genderTitle: 'Gender',
    genderUnknown: 'Unknown',
    genderMale: 'Male',
    genderFemale: 'Female',
    editPlaceholderNickname: 'Enter nickname',
    editPlaceholderMobile: 'Enter phone number',
    editPlaceholderEmail: 'Enter email',
    editPlaceholderSignature: 'Enter signature',
    mobileFormatError: 'Enter a valid phone number',
    emailFormatError: 'Enter a valid email',
    profileTitleNickname: 'Nickname',
    profileTitleMobile: 'Phone',
    profileTitleEmail: 'Email',
    profileTitleSignature: 'Signature',
    commonLoadingFailed: 'Load failed',
    commonActionFailed: 'Action failed',
    commonOpenFailed: 'Open failed',
    commonCreateFailed: 'Create failed',
    commonSendFailed: 'Send failed',
    commonDeleteFailed: 'Delete failed',
    commonRetry: 'Retry',
    commonSelect: 'Select',
    commonSearch: 'Search',
    commonEdit: 'Edit',
    commonClear: 'Clear',
    commonAgree: 'Agree',
    commonReject: 'Reject',
    commonRemove: 'Remove',
    commonDelete: 'Delete',
    commonExit: 'Exit',
    commonDismiss: 'Dismiss',
    commonTip: 'Notice',
    commonUnknownAccount: 'Unknown account',
    commonNotSet: 'Not set',
    commonGroupChat: 'Group chat',
    commonUnnamedGroupChat: 'Unnamed group chat',
    commonMessageMark: 'Pins',
    commonMessageHistory: 'History',
    commonEnableMessageNotification: 'Enable notifications',
    commonChatStickTop: 'Pin chat to top',
    commonAddToBlacklist: 'Add to blacklist',
    commonViewFriendCard: 'View friend card',
    commonAccountLabel: 'Account: {account}',
    commonAccountText: 'Account:{account}',
    commonNicknameText: 'Nickname: {name}',
    commonSearchFriendsPlaceholder: 'Search friends',
    commonSearchKeywordPlaceholder: 'Enter keywords to search',
    commonNoMatchingFriends: 'No matching friends found',
    commonNoSearchResults: 'No results',
    commonNoFriends: 'No friends yet',
    commonSearchResult: 'Search results',
    commonFriend: 'Friends',
    commonTeam: 'Groups',
    commonUserNotFound: 'User not found',
    commonCreateWithCount: 'Create ({count})',
    commonCreate: 'Create',
    commonSelectedCount: '{count} selected',
    commonSelectUpToCount: 'Up to {count} can be selected',
    commonTapAvatarToDeselect: 'Tap an avatar to deselect',
    commonSeedMembersAutoJoin: 'The current chat member will be added automatically',
    commonAtMostSelectContacts: 'You can select up to {count} contacts',
    commonSelectContactsFirst: 'Please select contacts',
    commonAiUserLabel: 'AI user · {account}',
    commonPermissionDenied: 'Permission required',
    commonOpenSettings: 'Open Settings',
    commonGrantPermissionInSettings: 'Please enable {permission} permission in Settings',
    commonPermissionCamera: 'Camera',
    commonPermissionAlbum: 'Photos',
    commonPermissionMicrophone: 'Microphone',
    commonNetworkUnavailable: 'Network unavailable. Please check your network settings.',
    sdkErrorAccountNotExist: 'This account does not exist',
    sdkErrorUserProfileNotExist: 'This user profile does not exist',
    sdkErrorFriendApplicationNotExist: 'The friend request does not exist',
    sdkErrorFriendNotExist: 'This friend does not exist',
    sdkErrorFriendAlreadyExist: 'This user is already your friend',
    sdkErrorSelfFriendOperationNotAllowed: 'You cannot perform this friend action on yourself',
    sdkErrorFriendLimit: 'Friend limit reached',
    sdkErrorTeamMemberLimit: 'Group member limit reached',
    sdkErrorJoinedTeamLimit: 'Joined team limit exceeded',
    sdkErrorTeamNotExist: 'Team does not exist',
    sdkErrorAlreadyInTeam: 'Already in the team',
    sdkErrorInvitationExpired: 'Invitation expired',
    sdkErrorVerificationProcessed: 'The verification message has been processed.',
    sdkErrorFriendOperationRateLimit: 'Friend actions are too frequent. Try again later.',
    sdkErrorFriendHitAntispam:
      'The friend request may contain sensitive content. Please edit it and try again.',
    sdkErrorSelfBlockListOperationNotAllowed: 'You cannot add yourself to the blocklist',
    sdkErrorBlockListLimit: 'Blocklist limit reached',
    sdkErrorMessageNotExist: 'This message does not exist',
    sdkErrorPinNotExist: 'This pinned message does not exist',
    sdkErrorPinAlreadyExist: 'This message is already pinned',
    sdkErrorPinLimit: 'Pinned message limit reached',
    sdkErrorRevokeExpired: 'The recall time limit has expired',
    sdkErrorRevokeNotAllowed: 'This message cannot be recalled',
    sdkErrorAccountInBlockList: 'The recipient has blocked you. Message sending failed.',
    sdkErrorOperationRateLimit: 'Actions are too frequent. Try again later.',
    sdkErrorAntispam:
      'The content may contain sensitive information. Please edit it and try again.',
    sdkErrorFileUploadFailed: 'File upload failed. Please try again later.',
    sdkErrorConnectFailed: 'Connection failed. Please check your network and try again.',
    sdkErrorProtocolSendFailed: 'Request sending failed. Please try again later.',
    sdkErrorRequestFailed: 'Request failed. Please try again later.',
    sdkErrorCallbackFailed: 'Callback processing failed. Please try again later.',
    sdkErrorInvalidParameter: 'Invalid parameter. Please check and try again.',
    sdkErrorTimeout: 'Request timed out. Please try again later.',
    sdkErrorConversationNotExist: 'Conversation does not exist',
    sdkErrorResourceNotExist: 'Resource does not exist',
    sdkErrorResourceAlreadyExist: 'Resource already exists',
    sdkErrorNoPermission: 'No permission for this operation',
    sdkErrorOperationNotAllowed: 'This operation is not allowed',
    sdkErrorUnsupported: 'This operation is not supported yet',
    sdkErrorFeatureNotEnabled: 'Feature not enabled',
    sdkErrorAccountBanned: 'User banned',
    sdkErrorAccountChatBanned: 'User chat banned',
    sdkErrorTeamMemberNotExist: 'Team member does not exist',
    sdkErrorTeamNormalMemberChatBanned: 'Team normal member chat banned',
    sdkErrorTeamMemberChatBanned: 'Team member chat banned',
    sdkErrorAIRequestLLMFailed: 'AI model request failed',
    sdkErrorAIMessagesDisabled: 'AI messaging function not enabled',
    sdkErrorNotAIAccount: 'Not an AI account',
    sdkErrorAIBlocklistNotAllowed: 'Cannot blocklist an AI account',
    sdkErrorAIRobotTokenInvalid: 'AI robot token is invalid',
    sdkErrorAIRobotBindCodeNotExist: 'AI robot account bind code does not exist',
    sdkErrorAIRobotNotBelongToUser: 'AI robot account does not belong to current user',
    sdkErrorAIRobotQRCodeAlreadyBound: 'This QR code has already been bound',
    commonOnline: 'Online',
    commonOffline: 'Offline',
    offlineText: 'Network unavailable. Please check your network settings.',
    connectingText: 'IM is disconnected and reconnecting...',
    commonStatusPending: 'Pending',
    commonStatusAgreed: 'Accepted',
    commonStatusRejected: 'Rejected',
    commonStatusExpired: 'Expired',
    commonStatusDirectAdded: 'Added directly',
    commonUnknownMessageBody: '[Unknown message]',
    commonMergedChatHistory: '[Chat history]',
    commonTextMessage: '[Text message]',
    commonImageMessage: '[Image message]',
    commonAudioMessage: '[Voice message]',
    commonVideoMessage: '[Video message]',
    commonLocationMessage: '[Location]',
    commonFileMessage: '[File] {name}',
    commonVideoCallMessage: '[Video call]',
    commonAudioCallMessage: '[Audio call]',
    commonAudioVideoCallMessage: '[Audio/video call]',
    commonImageShort: '[Image]',
    commonAudioShort: '[Voice]',
    commonLocationShort: '[Location]',
    commonFileShort: '[File]',
    commonReceiveNewMessage: 'You received a new message',
    commonSendFailedShort: '[Send failed]',
    commonSensitiveContentBlocked:
      'The content may contain sensitive information. Please revise it and try again.',
    commonSensitiveContentBlockedWithType:
      'The content may involve {type}. Please adjust and send.',
    commonAntispamPornography: 'Pornography',
    commonAntispamAdvertising: 'Advertising',
    commonAntispamAdvertisingLaw: 'Advertising Law',
    commonAntispamViolence: 'Violence and terrorism',
    commonAntispamProhibited: 'Prohibited',
    commonAntispamPolitics: 'Political-related',
    commonAntispamAbuse: 'Abuse',
    commonAntispamSpam: 'Spam',
    commonAntispamOther: 'Others',
    commonAntispamValue: 'Value-related',
    commonRecallByYou: 'You recalled a message',
    commonRecallByOther: 'The other party recalled a message',
    commonRecalledMessage: 'This message was recalled',
    commonReplySourceMissing: 'The original replied message no longer exists and cannot be resent',
    commonReplySourceUnavailable: 'The original replied message was recalled or deleted',
    commonOriginalImageMissing: 'The original image no longer exists and cannot be resent',
    commonOriginalVideoMissing: 'The original video no longer exists and cannot be resent',
    commonOriginalFileMissing: 'The original file no longer exists and cannot be resent',
    commonOriginalAudioMissing: 'The original voice message no longer exists and cannot be resent',
    commonOriginalLocationMissing: 'The original location no longer exists and cannot be resent',
    commonMessageForwardUnsupported: 'This message type does not support forwarding yet',
    messageStoreBlacklistedTip: 'The other party has blacklisted you. Message sending failed.',
    messageStoreFriendDeletedTip:
      'The friendship has been removed. Please send a friend request to continue chatting.',
    messageStoreReminderMessage: '[Reminder]',
    loginTitle: 'SMS Login',
    loginHint:
      'An unregistered mobile number will be registered automatically after SMS verification.',
    loginMobilePlaceholder: 'Enter mobile number',
    loginSmsCodePlaceholder: 'Enter verification code',
    loginRequestSmsCode: 'Get code',
    loginRequestSmsCodeCountdown: 'Retry in {count}s',
    loginButton: 'Log in',
    loginSigningInHint: 'Signing in and syncing basic data. Please wait.',
    loginInvalidSmsRequestMobile: 'Enter a valid mobile number',
    loginInvalidMobile: 'Enter a valid mobile number',
    loginInvalidSmsCode: 'Enter a valid verification code',
    loginSmsCodeFailed: 'Failed to get verification code',
    loginFailed: 'Login failed',
    loginOpenServiceFailed: 'Failed to open service agreement',
    loginOpenPrivacyFailed: 'Failed to open privacy policy',
    loginConsentTitle: 'Reminder',
    loginConsentBodyPrefix:
      'This mobile number has not been registered. By continuing, you confirm that you have read and agreed to the ',
    loginConsentService: 'Service Agreement',
    loginConsentAnd: ' and ',
    loginConsentPrivacy: 'Privacy Policy',
    loginConsentBodySuffix: '.',
    loginConsentDisagree: 'Disagree',
    loginConsentAgree: 'Agree',
    p2pSettingsTitle: 'Chat settings',
    teamSettingsTitle: 'Settings',
    teamSettingsLoadFailed: 'Failed to load group settings',
    teamInfoTitle: 'Group info',
    teamDiscussionInfoTitle: 'Discussion info',
    teamSettingsMemberCount: 'Members',
    teamSettingsDiscussionMemberCount: 'Discussion members',
    teamSettingsGroupId: 'Group ID: {teamId}',
    teamSettingsIntro: 'Group intro',
    teamSettingsMyNick: 'My group nickname',
    teamSettingsMyNickEditTitle: 'My nickname in this group',
    teamSettingsAvatar: 'Group avatar',
    teamSettingsDiscussionAvatar: 'Discussion avatar',
    teamSettingsName: 'Group name',
    teamSettingsDiscussionName: 'Discussion name',
    teamSettingsManage: 'Group management',
    teamSettingsChatBanned: 'Mute all members',
    teamSettingsInviteMode: 'Who can invite others',
    teamSettingsAddMemberMode: 'Who can add group members',
    teamSettingsUpdateInfoMode: 'Who can edit group info',
    teamSettingsAgreeMode: 'Invitee approval required',
    teamSettingsInviteModeManager: 'Owner and admins',
    teamSettingsInviteModeOwnerAndManager: 'Owner and admins',
    teamSettingsInviteModeAll: 'Everyone',
    teamSettingsAgreeModeNeed: 'Required',
    teamSettingsAgreeModeNoNeed: 'Not required',
    updateTeamAtText: 'Who can @ everyone',
    teamSettingsExitDiscussion: 'Leave discussion',
    teamSettingsDismissGroup: 'Dismiss group',
    teamSettingsExitGroup: 'Leave group',
    teamSettingsExitDiscussionConfirm: 'Leave this discussion?',
    teamSettingsDismissGroupConfirm: 'Dismiss this group?',
    teamSettingsExitGroupConfirm: 'Leave this group?',
    teamInviteMembersFailed: 'Invite failed',
    teamInviteCandidatesLoadFailed: 'Failed to load invite candidates',
    teamInviteCandidatesNoMatch: 'No invite candidates found',
    teamInviteCandidatesEmpty: 'No invite candidates',
    teamInviteSelectionHint: 'Selected contacts will be invited to the group directly',
    teamMemberRemoveTitle: 'Remove member',
    teamMemberRemoveConfirm: 'This member will leave the current group chat after removal.',
    teamMembersLoadFailed: 'Failed to load members',
    teamEditIntroPlaceholder: 'Enter group intro',
    teamEditNickPlaceholder: 'Enter my group nickname',
    teamEditAvatarTitle: 'Edit avatar',
    contactsBlacklistTitle: 'Blacklist',
    contactsBlacklistTip: 'You will not receive messages from any contacts in this list.',
    contactsBlacklistEmpty: 'No blacklisted contacts',
    contactsBlacklistPickerEmpty: 'No selectable friends',
    contactsBlacklistAddFailed: 'Failed to add to blacklist',
    contactsBlacklistLoadFailed: 'Failed to load blacklist',
    contactsBlacklistRemoveTitle: 'Remove from blacklist',
    contactsBlacklistRemoveConfirm: 'Remove this contact from the blacklist?',
    contactsValidListTitle: 'Verification messages',
    contactsValidListEmpty: 'No verification messages',
    contactsValidListLoadFailed: 'Failed to load verification messages',
    contactsValidListClearTitle: 'Clear verification messages',
    contactsValidListClearConfirm: 'Clear all current verification records?',
    contactsValidListClearFailed: 'Failed to clear',
    contactsValidListClearSuccess: 'Cleared successfully',
    contactsValidListRejectFailed: 'Failed to reject',
    contactsValidListAcceptFailed: 'Failed to accept',
    contactsValidListFriendRequest: '{name} friend request',
    contactsValidListFriendRequestAction: 'Requested to add you as a friend',
    contactsValidListAgreedYourRequest: '{name} accepted your friend request',
    contactsValidListRejectedYourRequest: '{name} rejected your friend request',
    friendAcceptGreetingText: "I've accepted your friend request. Now let's chat",
    friendRemarkTitle: 'Remark',
    contactsTeamListTitle: 'My groups',
    contactsTeamListEmpty: 'No groups yet',
    contactsTeamListLoadFailed: 'Failed to load groups',
    contactsTeamListInvalidConversation: 'This group conversation is unavailable',
    contactsAiUsersTitle: 'My AI users',
    contactsAiUsersEmpty: 'No AI users',
    contactsAiUsersLoadFailed: 'Failed to load AI users',
    contactsAiUsersInvalidConversation: 'This AI user conversation is unavailable',
    aiUserCardTitle: 'AI profile',
    friendCardTitle: 'Friend card',
    strangerCardTitle: 'Stranger card',
    friendCardAlias: 'Alias',
    friendCardBirthday: 'Birthday',
    friendCardMobile: 'Phone',
    friendCardEmail: 'Email',
    friendCardSignature: 'Signature',
    friendCardMessageNotification: 'Message notifications',
    friendCardChat: 'Chat',
    friendCardDelete: 'Delete friend',
    friendCardDeleteConfirm: 'Delete contact {name}?',
    friendCardAdd: 'Add friend',
    friendCardAddSentTitle: 'Sent',
    friendCardAddSentBody: 'Friend request sent',
    friendCardDefaultPostscript: 'Hi, I am an RN Demo user.',
    friendAddTitle: 'Add friend',
    friendAddPlaceholder: 'Enter account',
    friendAddEmptyTitle: 'No matching account found',
    friendAddEmptySubtitle: 'Please verify that the account you entered is correct.',
    conversationSearchTitle: 'Search',
    conversationSearchCreateTeam: 'Create group',
    conversationSearchInvalidFriend:
      'This contact is no longer valid. Please choose another valid contact.',
    conversationSearchLeftTeam:
      'You have been removed from the group or the group has been dismissed.',
    conversationPickerCancel: 'Cancel',
    conversationPickerNoSelectableFriends: 'No friends available to select',
    conversationListTitle: 'NIM Demo',
    conversationListNoMessage: 'No messages',
    conversationListPin: 'Pin',
    conversationListUnpin: 'Unpin',
    conversationListPinConversation: 'Pin conversation',
    conversationListDeleteConversation: 'Delete conversation',
    conversationListDeletingConversation: 'Deleting...',
    conversationListCurrentConversation: 'Current conversation',
    conversationListDeleteConfirmTitle: 'Delete conversation "{title}"',
    conversationListAddFriend: 'Add friend',
    conversationListJoinGroup: 'Join group',
    conversationListCreateDiscussion: 'Create discussion',
    conversationListCreateAdvancedGroup: 'Create advanced group',
    conversationListOperationFailedTitle: 'Action failed',
    conversationListDeleteFailedTitle: 'Delete failed',
    teamJoinTitle: 'Join group',
    teamJoinPlaceholder: 'Enter group ID',
    teamJoinSearchEmpty: 'Enter a group ID before searching',
    teamJoinNoResult: 'This group does not exist',
    teamJoinApply: 'Apply to join',
    teamJoinAlreadyJoined: 'Joined',
    teamJoinGoChat: 'Go to Chat',
    teamJoinGoChatFailed: 'Go to chat failed',
    teamJoinApplySuccess: 'Join request sent',
    teamJoinApplyFailed: 'Failed to apply to join',
    teamTypeDiscussion: 'Discussion',
    teamTypeAdvanced: 'Group',
    conversationPickerCreateDiscussionTitle: 'Create discussion',
    conversationPickerCreateAdvancedTitle: 'Create advanced group',
    conversationPickerCreateDiscussionAction: 'Create discussion',
    conversationPickerCreateAdvancedAction: 'Create advanced group',
    contactsHomeSummary: 'Friends {friendCount} · Groups {teamCount}',
    conversationMentionPrefix: '[Mentioned Me] ',
    conversationMentionBadge: '[Mentioned Me]',
    toolbarVoice: 'Voice',
    toolbarEmoji: 'Emoji',
    toolbarMore: 'More',
    commonSendFailedLabel: 'Send failed',
    commonTipMessagePreview: '[Tip message]',
    commonUnknownSize: 'Unknown size',
    commonUnknownShort: 'Unknown',
    commonDownloading: 'Downloading...',
    commonDownload: 'Download',
    commonPlay: 'Play',
    commonSending: 'Sending...',
    commonDurationLabel: 'Duration {duration}',
    commonFileMessageLabel: 'File message',
    commonVideoMessageLabel: 'Video message',
    commonDownloadedSize: 'Downloaded · {size}',
    chatMergedForwardFooter: 'Chat history',
    chatPinnedByYou: 'You pinned this message',
    chatPinnedMessage: 'pinned this message',
    chatSecurityTip:
      'This demo is for product experience only. Be cautious of transfers, prizes, or unknown calls to avoid scams.',
    chatSecurityTipReportLink: 'Report.',
    chatNonFriendTip: 'You are not friends yet, please protect your personal privacy and security',
    chatTeamDismissedTip: 'This group has been dismissed',
    chatTeamUnavailableTip: 'This group has been dismissed or you are no longer a member',
    chatTeamBannedPlaceholder: 'The group owner has muted all members',
    chatTimeLabelSameYear: '{month}/{day} {time}',
    chatTimeLabelFullYear: '{year}/{month}/{day} {time}',
    chatUnsupportedFormat: 'This format is not supported',
    chatVideoTooLarge: 'Videos larger than 100 MB cannot be sent',
    chatActionCopy: 'Copy',
    chatActionReply: 'Reply',
    chatActionForward: 'Forward',
    chatActionPin: 'Pin',
    chatActionUnpin: 'Unpin',
    chatActionMultiSelect: 'Multi-select',
    chatActionCollect: 'Collect',
    chatActionUncollect: 'Remove from collection',
    chatActionResend: 'Resend',
    chatActionRevoke: 'Recall',
    chatEmptyMessageUnsupported: 'Empty messages are not supported',
    chatSendMessageFailed: 'Message sending failed',
    chatMixedMediaUnsupported: 'Images and videos cannot be selected together',
    chatSingleVideoOnly: 'Only one video can be selected at a time',
    chatSendMediaFailed: 'Media sending failed',
    chatSendOriginalVideoFailed: 'Original video sending failed',
    chatSendOriginalImageFailed: 'Original image sending failed',
    chatLimitedPhotoAccessTitle: 'Limited photo access',
    chatLimitedPhotoAccessMessage:
      'Only authorized photos are currently available. You can continue selecting or add more photos.',
    chatChoosePhotos: 'Choose',
    chatAddMorePhotos: 'Add more photos',
    chatLimitedPhotoAccessUnsupported:
      'This environment does not support extending accessible photos directly. Adjust photo permissions in system settings.',
    chatLimitedMediaPickerTitle: 'Photos and Videos',
    chatFileAlbumPickerTitle: 'Album Files',
    chatLimitedMediaPickerEmpty: 'No authorized photos or videos are available',
    chatLimitedMediaPickerConfirm: 'OK',
    chatLimitedMediaPickerLoading: 'Loading authorized media...',
    chatSelectMediaUpToCount: 'Up to {count} items can be selected',
    chatOpenCameraActionsTitle: 'Capture',
    chatTakePhoto: 'Take photo',
    chatRecordVideo: 'Record video',
    chatFileSourceTitle: 'Choose file source',
    chatFileSourceAlbum: 'Choose from Album',
    chatFileSourceICloud: 'Choose from iCloud',
    chatFileTooLarge: 'The selected file exceeds the 100 MB limit. Please choose another file.',
    chatUploadRequestTooLarge: 'The file is too large to send.',
    chatSendFileFailed: 'File sending failed',
    chatNativeLocationUnavailableTitle: 'Native map unavailable',
    chatNativeLocationUnavailableMessage:
      'NIMLocationPicker is not registered in the current Android build. Rebuild and reinstall the app.',
    chatOpenNativeLocationFailedTitle: 'Failed to open AMap',
    chatOpenNativeLocationFailedMessage: 'Failed to open the native location picker',
    chatRecordFailedTitle: 'Recording failed',
    chatRecordStartFailed: 'Unable to start recording',
    chatRecordFileMissing: 'No voice file was generated for sending',
    chatRecordTooShort: 'Recording is too short',
    chatSendAudioFailed: 'Voice message sending failed',
    chatLoadEarlierMessagesFailed: 'Failed to load earlier messages',
    chatDetailTitle: 'Chat details',
    chatSourceMessageTitle: 'Source message',
    chatPeerTyping: 'Typing...',
    chatVoiceAction: 'Voice',
    chatImageAction: 'Image',
    chatMoreAction: 'More',
    chatSelectDoneCount: '{count} messages selected',
    chatPullToLoadHistory: 'Pull down to view earlier messages',
    chatNoMessages: 'No messages',
    chatNewMessageNotice: 'New messages',
    chatNewMessageNoticeCount: '{count} new messages',
    chatActionFailedTitle: 'Action failed',
    chatActionFailedMessage: 'The current action could not be completed',
    chatMentionSelectTitle: 'Select people to mention',
    chatMentionSearchPlaceholder: 'Search group members',
    chatMentionNoMatch: 'No group members found',
    chatMentionEmpty: 'No members available to mention',
    chatBatchForwardMerged: 'Merge forward',
    chatBatchForwardSerial: 'Forward one by one',
    chatReplyTo: 'Reply to {name}',
    chatVoiceReleaseToSend: 'Release to send. Slide out to cancel.',
    chatVoiceReleaseToCancel: 'Release to cancel sending.',
    chatVoiceProcessing: 'Processing...',
    chatHoldToTalk: 'Hold to talk',
    chatSendToConversation: 'Send to {name}',
    chatPanelCapture: 'Capture',
    chatPanelFile: 'File',
    chatPanelLocation: 'Location',
    chatOpenMessageFailed: 'Unable to open this message',
    chatReplySourceDownloading: 'Downloading',
    chatReeditExpired: 'The editable time window has expired',
    chatResendUnsupported: 'This message type cannot be resent yet',
    chatBatchForwardSerialLimit: 'A maximum of {count} messages can be forwarded one by one',
    chatBatchForwardMergedLimit: 'A maximum of {count} messages can be merge-forwarded',
    chatMergedForwardTrimConfirm:
      'Some messages exceed the merge-forward limit and cannot be merged. Remove them and continue?',
    chatForwardUnsupportedMessages: 'Some selected messages cannot be forwarded',
    chatBatchDeleteLimit: 'You can delete up to {count} messages at once',
    chatDeleteMessageTitle: 'Delete message',
    chatDeleteSelectedConfirm: 'Delete the selected messages?',
    chatDeleteSingleConfirm: 'Delete this message?',
    chatRevokeFailedTitle: 'Recall failed',
    chatRevokeExpired: 'The recall time limit has expired',
    chatRevokeMessageTitle: 'Recall message',
    chatRevokeConfirm: 'Recall this message?',
    chatPinSuccess: 'Pinned successfully',
    chatUnpinSuccess: 'Unpinned successfully',
    chatPinFailed: 'Pin failed',
    chatUnpinFailed: 'Unpin failed',
    chatCollectSuccess: 'Collected successfully',
    chatUncollectSuccess: 'Removed from collection',
    chatCollectFailed: 'Collect failed',
    chatUncollectFailed: 'Remove from collection failed',
    chatVideoUnavailable: 'This video is unavailable or not ready yet',
    chatDownloadingTitle: 'Please wait',
    chatVideoDownloading: 'The video is downloading',
    chatDownloadCompletedTitle: 'Download complete',
    chatVideoDownloaded: 'The video has been cached. Tap again to play.',
    chatVideoDownloadFailed: 'Video download failed',
    chatFileUnavailable: 'This file is unavailable or not ready yet',
    chatFileDownloading: 'The file is downloading',
    chatFileDownloaded: 'The file has been saved locally. Tap again to open it.',
    chatFileDownloadFailed: 'File download failed',
    chatFileOpenFailed: 'This file cannot be opened',
    chatAudioUnavailable: 'This voice message is unavailable or not ready yet',
    chatAudioPlayFailedTitle: 'Playback failed',
    chatAudioPlayFailed: 'This voice message cannot be played',
    chatCopySuccess: 'Copied',
    locationPickerCoordinateAddress: 'Location: {latitude}, {longitude}',
    locationPickerMapLoading: 'Loading map',
    locationPickerLocationFailedTitle: 'Location failed',
    locationPickerLocationFailedMessage: 'Search for a place or move the map to choose a location.',
    locationPickerSendUnavailableTitle: 'Unable to send',
    locationPickerSendUnavailableMessage: 'Please select a location.',
    locationPickerTitle: 'Choose location',
    locationPickerConversationUnavailableTitle: 'Conversation unavailable',
    locationPickerConversationUnavailableDescription:
      'Unable to send a location message for the current conversation.',
    locationPickerLocating: 'Locating...',
    locationPickerLoadingMap: 'Loading map...',
    locationPickerSearchPlaceholder: 'Search places',
    locationPickerPermissionTip:
      'Location permission is disabled. You can search for a place or move the map to choose one.',
    locationPickerSearching: 'Searching places...',
    locationPickerEmpty: 'No locations',
    readDetailLoadFailed: 'Failed to load read receipts',
    readDetailAllUnread: 'Everyone unread',
    readDetailAllRead: 'Everyone read',
    readDetailTitle: 'Message read status',
    readDetailEmptyTitle: 'No read status',
    readDetailEmptyDescription: 'There is no read/unread detail available for this message yet.',
    readDetailReadTab: 'Read ({count})',
    readDetailUnreadTab: 'Unread ({count})',
    readDetailRealtimeDescription: 'Read status updates in real time as receipts arrive.',
    mediaViewerMissingTitle: 'Media unavailable',
    mediaViewerMissingDescription: 'The current image or video has not finished syncing yet.',
    mediaViewerSaveFailedTitle: 'Save failed',
    mediaViewerMissingMedia: 'The media resource does not exist',
    mediaViewerSaveUnsupported:
      'Saving to the system album is not supported in Expo Go. Use a development build or native package to verify this feature.',
    mediaViewerNeedPhotoPermission: 'Enable photo library permission in system settings',
    mediaViewerSavedToAlbum: 'Saved to system album',
    mediaViewerSaveSuccessTitle: 'Saved',
    mediaViewerOpenFailedTitle: 'Open failed',
    mediaViewerOriginalMissing: 'The original media URL does not exist',
    mediaViewerOriginalAddressTitle: 'Original URL',
    mediaViewerImageMissingTitle: 'Image unavailable',
    mediaViewerImageMissingDescription: 'Return to the chat page and try opening it again.',
    mediaViewerImageSaveFailed: 'Image save failed',
    mediaViewerVideoSaveFailed: 'Video save failed',
    mediaViewerVideoMissingTitle: 'Video unavailable',
    mediaViewerVideoMissingDescription: 'Return to the chat page and try opening it again.',
    fileDetailSourceChat: 'Files in chat',
    fileDetailSourceCollection: 'Files in collection',
    fileDetailSendToCurrentConversation: 'Send to current conversation',
    fileDetailSavedTitle: 'File saved',
    fileDetailDownloadSuccessTitle: 'Download complete',
    fileDetailSavedDescription: 'The file has been saved locally',
    fileDetailDownloadFailed: 'Failed to save the file',
    fileDetailUnavailableTitle: 'File unavailable',
    fileDetailUnavailableDescription:
      'The current file has not finished syncing yet. Try again later.',
    fileDetailChatHint: 'This shows the file from the current chat message.',
    fileDetailCollectionHint:
      'This shows the collection shell for the opened file. A real collection list can be connected later.',
    fileDetailOpeningStatus: 'Opening file',
    fileDetailDownloadingStatus: 'Downloading file',
    fileDetailDownloadedStatus: 'Downloaded and ready to open',
    fileDetailPendingStatus: 'Not downloaded. It will be cached automatically when opened.',
    fileDetailOpening: 'Opening...',
    fileDetailOpenFile: 'Open file',
    fileDetailDownloadAndOpen: 'Download and open',
    fileDetailSaving: 'Saving...',
    fileDetailSaved: 'Saved',
    fileDetailSaveFile: 'Save file',
    forwardModeSerial: 'Forward one by one',
    forwardModeMerged: 'Merge forward',
    forwardModeSingle: 'Forward',
    forwardGroupMemberCount: '{count} members',
    forwardNoMessages: 'No messages available to forward',
    forwardPreviewConversationRecord: '[{mode}] {title} chat history',
    forwardRecentLoadFailed: 'Failed to load recent forwards',
    forwardUnavailableTitle: 'Unable to forward',
    forwardUnavailableMessage:
      'The target conversation is no longer valid. Please choose another valid contact or group.',
    forwardMaxTargets: 'You can select up to {count} conversations',
    forwardSelectAtLeastOne: 'Please select at least one valid conversation',
    forwardSelectValidTarget: 'Please select a valid conversation to forward to',
    forwardFailedTitle: 'Forward failed',
    forwardUnsupportedFormat: 'This format is not supported yet',
    forwardMergedLimitExceeded:
      'Some messages exceed the merge-forward limit and cannot be merge-forwarded',
    forwardSystemFailure: 'A system error occurred. Forwarding failed',
    forwardHeaderSelect: 'Select',
    forwardHeaderMultiSelect: 'Multi-select',
    forwardSelectedConversations: '{count} conversations selected',
    forwardSectionRecent: 'Recent forwards',
    forwardSectionRecentChats: 'Recent chats',
    forwardSectionFriends: 'My friends',
    forwardSectionGroups: 'My groups',
    forwardRecentLoadFailedTitle: 'Failed to load recent forwards',
    forwardSearchNoResultPrefix: 'No results for ',
    forwardSearchNoResultSuffix: '',
    forwardNoConversations: 'No conversations',
    forwardNoConversationsDescription:
      'After entering chats, you can quickly forward from recent conversations here.',
    forwardNoFriendsDescription: 'Add friends before forwarding messages.',
    forwardNoGroups: 'No groups',
    forwardNoGroupsDescription: 'Join a group to forward messages there.',
    forwardSendToTitle: 'Send to',
    forwardCommentPlaceholder: 'Leave a note',
    forwardSelectedTitle: 'Selected',
    forwardSelectedEmpty: 'No conversations selected',
    collectionTitle: 'Collection',
    collectionImageBadge: 'Image',
    collectionImageHelper: 'Image message preview',
    collectionVideoBadge: 'Video',
    collectionVideoHelper: 'Video message preview',
    collectionFileBadge: 'File',
    collectionFileHelper: 'File message preview',
    collectionLocationBadge: 'Location',
    collectionLocationHelper: 'Location message preview',
    collectionLoadFailed: 'Failed to load collections',
    collectionEmptyTitle: 'No collections',
    collectionEmptySubtitle: 'Collected messages will appear here',
    collectionUnknownConversation: 'Unknown conversation',
    collectionOriginalMessageUnavailable:
      'The original message does not exist or has not synced yet',
    collectionPreviewFallback: 'Collected message',
    collectionUnknownSender: 'Unknown sender',
    collectionSourcePrefix: 'From {name}',
    collectionP2PSourcePrefix: 'From chat with {name}',
    collectionTeamSourcePrefix: 'From {name}',
    collectionRemoveFailed: 'Failed to delete collection',
    collectionRemoveAction: 'Delete',
    collectionDeleteConfirm: 'Delete this collection?',
    collectionDeleteSuccess: 'Deleted successfully',
    collectionResolveFailed: 'Failed to fetch information',
    collectionProcessing: 'Processing...',
    collectionForwardAction: 'Forward',
    mergedForwardDownloadFailed: 'Failed to download chat history',
    mergedForwardMessagesTitle: '{name} messages',
    mergedForwardTitleSuffix: "'s messages",
    mergedForwardNotFound: 'Chat history not found',
    mergedForwardFetchFailed: 'Failed to fetch information',
    mergedForwardAttachmentOpenUnsupported: 'This device cannot open the attachment directly',
    mergedForwardOpenMessageFailed: 'Unable to open this message',
    mergedForwardLoading: 'Loading...',
    mergedForwardUnavailableDescription:
      'The merged-forward content has not finished syncing locally yet.',
    conversationPreviewNoDetailAddress: 'No detailed address',
    chatReportTitle: 'Report',
    chatReportLoadFailed: 'Failed to load report page',
    chatReportLoadFailedDescription: 'Please check your network and try again.',
    commonReload: 'Reload',
    locationDetailUnavailableTitle: 'Location message unavailable',
    locationDetailUnavailableDescription:
      'The location data has not finished syncing yet. Please try again later.',
    locationDetailBack: 'Back',
    locationDetailNavigate: 'Navigate',
    locationDetailOpenFailed: 'Open failed',
    locationDetailNavigationUnavailable: 'Unable to navigate',
    locationDetailCoordinateUnavailable: 'Current location coordinates are unavailable',
    locationDetailMapUnavailable: 'No map app is available on this device',
    locationDetailMapOpenUnavailable: 'Unable to open the map',
    commonLocationTitle: 'Location',
    chatHistoryTitle: 'History',
    chatHistorySearchPlaceholder: 'Search chat history',
    chatHistoryCurrentConversation: 'Current conversation',
    chatHistorySummary: '{count} messages',
    chatHistoryLoadFailed: 'Failed to load chat history',
    chatHistoryLoadMoreFailed: 'Unable to load earlier messages',
    chatHistoryLoadMore: 'Load earlier messages',
    chatHistoryEmpty: 'No chat history',
    chatHistoryNoMatch: 'No matching history messages',
    chatHistoryNoMatchDescription: 'Try another keyword, or load earlier messages first.',
    chatHistoryAudioUnavailable: 'The voice message is unavailable',
    chatHistoryAttachmentUnavailable: 'This attachment cannot be opened directly on this device',
    commonMessageUnavailableOpen: 'This message cannot be opened',
    pinnedMessagesTitle: 'Pins',
    pinnedMessagesLoading: 'Loading...',
    pinnedMessagesSyncingDescription: 'Syncing pinned messages for this conversation.',
    pinnedMessagesLoadFailed: 'Failed to load pinned messages',
    pinnedMessagesEmpty: 'No pinned messages',
    pinnedMessagesEmptyDescription: 'Long press a message in chat to pin important content here.',
    pinnedMessagesUnpinFailed: 'Failed to unpin message',
    pinnedMessagesCopyFailed: 'This message cannot be copied',
    messagePreviewTitle: 'Message details',
    messagePreviewMissingTitle: 'Message unavailable',
    messagePreviewMissingDescription:
      'The content has not finished syncing locally yet. Please try again later.',
    messagePreviewOutgoingTitle: 'Content I sent',
    messagePreviewIncomingTitle: 'Message content',
    messagePreviewCopyContent: 'Copy content',
    messagePreviewCopyFailed: 'Failed to copy content',
    messagePreviewSendToConversation: 'Send to current conversation',
    messagePreviewSendToNamedConversation: 'Send to {name}',
    messagePreviewOriginalAddressLabel: 'Original URL',
    messagePreviewOriginalAddressCopyAction: 'Copy Full Original URL',
    messagePreviewOriginalAddressCopied: 'Original URL copied',
    messagePreviewOriginalAddressCopyFailed: 'Failed to copy original URL',
    messagePreviewOriginalAddressWarning: 'Keep it safe, do not share with others',
    teamNotificationJoinedGroup: '{name} joined the group',
    teamNotificationInviteMembers: '{inviter} invited {members} to join the group',
    teamNotificationInviteNewMembers: '{inviter} invited new members to join the group',
    teamNotificationMembersRemoved: '{members} were removed from the group',
    teamNotificationMemberRemoved: 'A member was removed from the group',
    teamNotificationLeftGroup: '{name} left the group',
    teamNotificationOwnerTransferred: '{name} became the new owner',
    teamNotificationOwnerTransferredFallback: 'The group owner was transferred',
    teamNotificationRenamedGroup: '{name} renamed the group to {groupName}',
    teamNotificationUpdatedAvatar: '{name} updated the group avatar',
    teamNotificationUpdatedIntro: '{name} updated the group introduction',
    teamNotificationUpdatedInfo: 'Group information was updated',
    teamNotificationUpdatedInviteMode:
      'updated group permission "Invite others permission" to "{value}"',
    teamNotificationUpdatedInfoMode:
      'updated group permission "Group information modification permission" to "{value}"',
    teamNotificationUpdatedChatBanned: 'updated "Group mute" to {value}',
    teamNotificationUpdatedAllowAt: 'updated @all permission to {value}',
    teamNotificationValueAll: 'All members',
    teamNotificationValueOwnerOnly: 'Owner only',
    teamNotificationValueOwnerAndManager: 'Owner and managers',
    teamNotificationValueOpen: 'On',
    teamNotificationValueClose: 'Off'
  }
} as const

const UIKIT_TRANSLATIONS = {
  zh: uikitZh,
  en: uikitEn
} as const

export type AppTranslationKey =
  | keyof typeof APP_TRANSLATIONS.zh
  | keyof typeof UIKIT_TRANSLATIONS.zh

export function getSystemLanguage() {
  try {
    return Intl.DateTimeFormat().resolvedOptions().locale || 'zh-CN'
  } catch {
    return 'zh-CN'
  }
}

export function resolveAppLanguage(
  preference: AppLanguagePreference,
  systemLanguage = getSystemLanguage()
): AppLanguage {
  if (preference === 'zh' || preference === 'en') {
    return preference
  }

  return systemLanguage.toLowerCase().startsWith('zh') ? 'zh' : 'en'
}

let activeAppLanguage: AppLanguage = 'zh'

export function setActiveAppLanguage(language: AppLanguage) {
  activeAppLanguage = language
}

export function getActiveAppLanguage() {
  return activeAppLanguage
}

export function translateApp(
  language: AppLanguage,
  key: AppTranslationKey,
  params?: Record<string, string | number>
): string {
  const appMap = APP_TRANSLATIONS[language] as Record<string, string>
  const appZhMap = APP_TRANSLATIONS.zh as Record<string, string>
  const uikitMap = UIKIT_TRANSLATIONS[language] as Record<string, string>
  const uikitZhMap = UIKIT_TRANSLATIONS.zh as Record<string, string>
  const template = String(appMap[key] || uikitMap[key] || appZhMap[key] || uikitZhMap[key] || key)

  if (!params) {
    return template
  }

  let result = template

  for (const [paramKey, paramValue] of Object.entries(params)) {
    result = result.replaceAll(`{${paramKey}}`, String(paramValue))
  }

  return result
}

export function translateCurrentApp(
  key: AppTranslationKey,
  params?: Record<string, string | number>
) {
  return translateApp(activeAppLanguage, key, params)
}
